# Generated by Django 2.2.8 on 2020-06-07 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(default='chapter', max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images', upload_to='notes/pdf_images')),
                ('term', models.CharField(choices=[('minor1', 'minor1'), ('minor2', 'minor2'), ('major', 'major')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eigth', 'Eigth')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(default='files', upload_to=notes.models.call_to_upload)),
                ('upload_date', models.DateField(default=datetime.date(2020, 6, 7))),
                ('rel_chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.Chapter')),
            ],
            options={
                'verbose_name': 'Pdf File',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cource_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course', models.CharField(default='course', max_length=30)),
                ('semester', models.ForeignKey(default='first', on_delete=django.db.models.deletion.CASCADE, to='notes.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='rel_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Course'),
        ),
    ]
